;; very shitty replacement for org agenda until I figure out how to use the damn thing
(defun timestamp-for-tomorrow ()
  (setq seconds-in-day (* 24 60 60))
  (setq tomorrow-seconds (+ seconds-in-day (time-convert (current-time) 'integer)))
  (time-convert tomorrow-seconds 'list))
(defun timestamp-for-yesterday ()
  (setq seconds-in-day (* 24 60 60))
  (setq tomorrow-seconds (- (time-convert (current-time) 'integer) seconds-in-day))
  (time-convert tomorrow-seconds 'list))
(defun timestamp-for-next-week ()
  (setq seconds-in-week (* 7 24 60 60))
  (setq tomorrow-seconds (+ seconds-in-day (time-convert (current-time) 'integer)))
  (time-convert tomorrow-seconds 'list))

(defun merdate-di-oggi ()
  (interactive)
  (find-file (format-time-string "/home/nil/notes/agenda/giorno/%Y-%m-%d.org" (current-time))))
(defun merdate-di-ieri ()
  (interactive)
  (find-file (format-time-string "/home/nil/notes/agenda/giorno/%Y-%m-%d.org" (timestamp-for-yesterday))))
(defun merdate-di-domani ()
  (interactive)
  (find-file (format-time-string "/home/nil/notes/agenda/giorno/%Y-%m-%d.org" (timestamp-for-tomorrow))))
(defun merdate-di-sta-settimana ()
  (interactive)
  (find-file (format-time-string "/home/nil/notes/agenda/settimana/%Y-%V.org" (current-time))))
(defun merdate-prossima-settimana ()
  (interactive)
  (find-file (format-time-string "/home/nil/notes/agenda/settimana/%Y-%V.org" (timestamp-for-next-week))))
(defun merdate-di-sto-mese ()
  (interactive)
  (find-file (format-time-string "/home/nil/notes/agenda/mese/%Y-%m.org" (current-time))))
(defun merdate-breve-termine ()
  (interactive)
  (find-file "/home/nil/notes/agenda/breve-termine.org"))
(defun merdate-lungo-termine ()
  (interactive)
  (find-file "/home/nil/notes/agenda/lungo-termine.org"))

;; shitty replacement for diary
(defun deareoggi ()
  (interactive)
  (find-file (format-time-string "/home/nil/notes/diario/giorno/%Y-%m-%d.org" (current-time))))

(add-hook 'diary-mode-hook 'visual-line-mode)
